(function () {
    var FLAG_FR = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 900 600'%3E%3Cpath fill='%23002395' d='M0 0h900v600H0z'/%3E%3Cpath fill='%23FFF' d='M300 0h600v600H300z'/%3E%3Cpath fill='%23ED2939' d='M600 0h300v600H600z'/%3E%3C/svg%3E";
    var FLAG_NL = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 900 600'%3E%3Cpath fill='%23AE1C28' d='M0 0h900v200H0z'/%3E%3Cpath fill='%23FFF' d='M0 200h900v200H0z'/%3E%3Cpath fill='%231E4785' d='M0 400h900v200H0z'/%3E%3C/svg%3E";
    var FLAG_EN = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 60 30'%3E%3Crect width='60' height='30' fill='%23012169'/%3E%3Cpath d='M0 0L60 30M60 0L0 30' stroke='%23fff' stroke-width='6'/%3E%3Cpath d='M30 0v30M0 15h60' stroke='%23fff' stroke-width='10'/%3E%3Cpath d='M30 0v30M0 15h60' stroke='%23C8102E' stroke-width='6'/%3E%3C/svg%3E";
    var FLAGS = { fr: FLAG_FR, nl: FLAG_NL, en: FLAG_EN };

    var T = {
        fr: {
            /* ── Logo subtitle ── */
            'logo-subtitle': 'Du groupe FB logistics',
            'fb-group-bar': 'Du groupe FB Logistics',

            /* ── Desktop nav ── */
            'nav-services': 'Services',
            'nav-process': 'Notre Process',
            'nav-fleet': 'Notre Flotte',
            'nav-about': 'Qui Sommes-Nous',
            'nav-news': 'News',
            'nav-quote': 'Faire un devis',

            /* ── Mobile menu ── */
            'menu-home': 'ACCUEIL',
            'menu-vehicles': 'VÉHICULES',
            'menu-services': 'NOS SERVICES',
            'menu-about': 'QUI SOMMES-NOUS ?',
            'menu-client': 'ACCÈS CLIENT',
            'menu-news': 'NEWS',
            'menu-call': 'APPELER',

            /* ── Hero ── */
            'hero-subtitle': 'Solutions de transport dédié et express, fiables et efficaces pour tous vos besoins logistiques',
            'hero-subtitle-mobile': 'Solutions de transport dédié et express,<br>fiables et efficaces',

            /* ── CTA ── */
            'cta-info': 'Besoin d\'une solution rapide ?',
            'btn-quote': 'Faire un devis',
            'btn-contact': 'Nous contacter',

            /* ── Services ── */
            'services-title': 'NOS SERVICES',
            'services-tagline': 'Des solutions adaptées à chaque besoin',
            'services-tagline-mobile': 'Des solutions adaptées<br>à vos besoins',
            'svc-transport-name': 'Transport',
            'svc-transport-desc': 'Solutions de transport national et international adaptées à vos besoins',
            'svc-transport-desc-mobile': 'national &amp; international',
            'svc-eco-name': 'Économique',
            'svc-eco-desc': 'Le meilleur rapport qualité/prix pour vos envois professionnels',
            'svc-eco-desc-mobile': 'Le meilleur rapport qualité / prix',
            'svc-quote-name': 'BESOIN D\'UN DEVIS ?',
            'svc-quote-desc': 'Contactez-nous dès maintenant pour une offre personnalisée',
            'svc-quote-desc-mobile': 'Contactez-nous dès maintenant<br>pour une offre personnalisée',

            /* ── Process ── */
            'process-subtitle': 'de la réception à la livraison',
            'step1-name': 'RÉCEPTION',
            'step1-desc': '→ Contact client<br>→ Prise en commande',
            'step1-desc-mobile': '→ Contact client<br>→ Prise en commande',
            'step2-name': 'PRÉPARATION',
            'step2-name-mobile': 'PRÉPARATION',
            'step2-desc': '→ Attribution du chauffeur<br>→ Trajet vers le point de chargement<br>→ Chargement du véhicule',
            'step2-desc-mobile': '→ Attribution chauffeur<br>→ Point de chargement<br>→ Chargement',
            'step3-name': 'LIVRAISON',
            'step3-desc': '→ Trajet vers la destination<br>→ Déchargement<br>→ Signature POD (Proof of Delivery)',
            'step3-desc-mobile': '→ Trajet destination<br>→ Déchargement<br>→ Signature POD',

            /* ── Fleet ── */
            'fleet-title': 'NOTRE FLOTTE',
            'fleet-subtitle': 'DE VÉHICULES',
            'fleet-tagline': 'Des solutions adaptées à chaque besoin de transport',
            'fleet-tagline-mobile': 'Des solutions adaptées à chaque besoin<br>de transport',
            'fleet-cta': 'CHOISISSEZ LE VÉHICULE ADAPTÉ À VOTRE BESOIN',
            'fleet-cta-mobile': 'CHOISISSEZ LE VÉHICULE<br>ADAPTÉ À VOTRE BESOIN',
            'veh1-name': 'VOITURE',
            'veh1-desc': 'Idéale pour les petits déplacements et livraisons rapides en milieu urbain',
            'veh1-desc-mobile': 'Idéale pour les petits déplacements<br>et livraisons rapides.',
            'veh2-name': 'CAMIONNETTE 9 M³ / 4',
            'veh2-desc': 'Volume optimal pour transport plus important, en toute sécurité',
            'veh2-desc-mobile': 'Volume optimal pour transport<br>plus important, en toute sécurité.',
            'veh3-name': 'CAMIONNETTE 2,70 m³ / 450 kg',
            'veh3-desc': 'Parfaite pour les petits transports et livraisons quotidiennes',
            'veh3-desc-mobile': 'Parfaite pour les petits transports et<br>livraisons.',
            'veh4-name': 'CAMIONNETTE 6 M³ / 4',
            'veh4-desc': 'Idéale pour vos déménagements et livraisons du quotidien',
            'veh4-desc-mobile': 'Idéale pour vos déménagements<br>et livraisons du quotidien.',

            /* ── Fleet modal ── */
            'veh1-type': 'VOITURE',           'veh1-subtitle': 'Berline / Citadine',       'veh1-badge': 'Idéal pour courriers rapides',
            'veh2-type': 'CAMIONNETTE',        'veh2-subtitle': 'Fourgon / Grand Volume',   'veh2-badge': 'Idéal pour grands volumes',
            'veh3-type': 'UTILITAIRE',         'veh3-subtitle': 'Fourgon / Compact',        'veh3-badge': 'Idéal pour petits volumes',
            'veh4-type': 'CAMIONNETTE',        'veh4-subtitle': 'Fourgon / Standard',       'veh4-badge': 'Idéal pour déménagements',
            'spec-table-title': 'SPÉCIFICATIONS TECHNIQUES',
            'spec-label-volume': 'Volume utile',
            'spec-label-payload': 'Charge utile',
            'spec-label-security': 'Sécurité',
            'spec-security-value': 'Optimale',
            'spec-length': 'Longueur intérieure',
            'spec-height': 'Hauteur intérieure',
            'spec-width-wheels': 'Largeur intérieure entre roues',
            'spec-width-load': 'Largeur de chargement',
            'spec-volume': 'Volume utile',
            'spec-payload': 'Charge utile',
            'veh-select-btn': 'Sélectionner ce véhicule',

            /* ── About / Stats ── */
            'stat-vehicles': 'Véhicules',
            'stat-experience': 'Années d\'expérience',
            'stat-solution': 'Solution unique',
            'stat-clients': 'Clients satisfaits',
            'stat-vehicles-m': 'véhicules',
            'stat-exp-m': 'années<br>d\'expérience',
            'stat-sol-m': 'solution<br>unique',
            'stat-clients-m': 'Clients',
            'about-title': 'QUI SOMMES-NOUS ?',
            'about-title-mobile': 'QUI SOMMES<br>NOUS ?',
            'about-p1': 'Depuis plus de 25 ans, <span class="highlight">Number One</span> est spécialiste du transport express en Belgique et en Europe.',
            'about-p2': '<span class="highlight">De 1 gramme à 30 tonnes</span>, nous prenons en charge tous vos envois, du courrier à la marchandise volumineuse.',
            'about-p3': 'Notre flotte complète — de la simple voiture au semi-remorque — et notre équipe de 70 professionnels sont à votre service pour chaque envoi.',
            'about-p4': '<span class="highlight">Fiabilité, rapidité</span> et rigueur : ce sont les valeurs qui font de nous un partenaire de confiance depuis plus de 25 ans.',
            'about-btn': 'En savoir plus',

            /* ── Welcome popup ── */
            'popup-title': 'Bienvenue chez Number One !',
            'popup-body': 'Vous êtes au bon endroit pour tous vos besoins de transport — national et international. De 1 gramme à 30 tonnes, nous livrons partout en Belgique et en Europe.',
            'popup-close': 'Découvrir nos services',

            /* ── Contact footer ── */
            'menu-services-link': 'Nos services',
            'menu-about-link': 'Qui sommes-nous ?',

            /* ── Calculator ── */
            'calc-step1-l1': 'MODE DE', 'calc-step1-l2': 'TARIFICATION',
            'calc-step1-sub': 'Choisissez le mode de tarification qui correspond à votre besoin',
            'calc-step2-l1': 'CARACTÉRISTIQUES', 'calc-step2-l2': 'DU CHARGEMENT',
            'calc-step2-sub': 'Décrivez votre chargement le plus précisément possible',
            'calc-step3-l1': 'SÉLECTION', 'calc-step3-l2': 'DU VÉHICULE',
            'calc-step3-sub': 'Choisissez le véhicule adapté à vos chargements',
            'calc-step4-l1': 'SUPPLÉMENTS', 'calc-step4-l2': 'OPÉRATIONNELS',
            'calc-step4-sub': 'Ajoutez les options et contraintes spécifiques à votre transport',
            'calc-step5-l1': 'CARBURANT', 'calc-step5-l2': '& TVA',
            'calc-step5-sub': 'Indiquez les options fiscales à inclure dans le calcul',
            'calc-sum-l1': 'RÉSUMÉ', 'calc-sum-l2': 'DU DEVIS',
            'calc-sum-sub': 'Récapitulatif complet de votre demande de transport',
            'calc-mode-bxl': 'Bruxelles / Brussel',
            'calc-mode-bxl-sub': 'Prix fixe ville',
            'calc-mode-prov-min': 'Province min.',
            'calc-mode-prov-min-sub': 'Tarif provincial fixe',
            'calc-mode-rand': 'Rand / Banlieue',
            'calc-mode-rand-sub': 'Prix périphérie',
            'calc-mode-prov-km': 'Province / Km',
            'calc-mode-prov-km-sub': 'Tarif par kilomètre',
            'calc-mode-navette': 'Navette',
            'calc-mode-navette-sub': 'Prix fixe navette',
            'calc-mode-dispo': 'Tournée / Dispo',
            'calc-mode-dispo-sub': 'Prix horaire',
            'calc-distance': 'Distance (km)',
            'calc-zone-navette': 'Zone navette',
            'calc-nav-bxl': 'Bxl / Brussel — €8.71',
            'calc-nav-rand': 'Banl. / Rand — €10.15',
            'calc-nav-brabant': 'Brabant — €15.94',
            'calc-nav-prov': 'Prov. — €19.93',
            'calc-nav-prov-lux': 'Prov. Lux. — €31.90',
            'calc-nav-export': 'Export (sur demande)',
            'calc-duree': 'Durée',
            'calc-duree-under6': 'Moins de 6h',
            'calc-duree-over6': '6h ou plus',
            'calc-heures': 'Heures',
            'calc-km-supp': 'Km supplémentaires',
            'calc-next': 'Suivant',
            'calc-back': '← Retour',
            'calc-palettes': 'PALETTES (PAL)',
            'calc-poids': 'POIDS (Kg)',
            'calc-hauteur': 'HAUTEUR',
            'calc-longueur': 'LONGUEUR',
            'calc-largeur': 'LARGEUR',
            'calc-volume': 'VOLUME (M³)',
            'calc-optional': '(optionnel)',
            'calc-frigo': 'Transport frigorifique',
            'calc-temp-range': 'Plage de température',
            'calc-hayon': 'Hayon requis',
            'calc-choose-vehicle': 'CHOISISSEZ LE VÉHICULE ADAPTÉ À VOTRE BESOIN',
            'calc-override': 'Sélection manuelle (override)',
            'calc-debug': '▶ Détails de sélection (afficher/masquer)',
            'calc-waiting': "TEMPS D'ATTENTE TOTAL (MIN)",
            'calc-stops-bxl': 'EXTRA ARRÊT BRUXELLES',
            'calc-stops-other': 'EXTRA ARRÊT AUTRES',
            'calc-supp-night': 'Supplément nuit',
            'calc-frigo-night-12': 'Nuit frigo -12/0°C',
            'calc-frigo-night-20': 'Nuit frigo 0/-20°C',
            'calc-convoyeur': 'CONVOYEUR (HEURES)',
            'calc-convoyeur-rate': '€40.89 / heure',
            'calc-chauffeur': '2e CHAUFFEUR (HEURES)',
            'calc-chauffeur-rate': '€47.93 / heure',
            'calc-fuel-label': 'Appliquer surcharge carburant',
            'calc-fuel-sub': 'Ajoutez la surcharge carburant au devis',
            'calc-fuel-pct': '% Surcharge carburant',
            'calc-fuel-warning': '⚠ Valeur variable — à vérifier mensuellement. Exemple déc. 2025 : 19,50 %',
            'calc-vat-label': 'Afficher le prix TTC (TVA 21 %)',
            'calc-vat-sub': 'Ajoutez la TVA au devis',
            'calc-resume': 'RÉSUMER',
            'calc-disclaimer': 'Ce calculateur est basé sur le tarif 2026. Le prix final reste soumis à vérification commerciale. Tous les prix sont hors TVA (21 %).',
            'calc-print': '🖨️ Imprimer',
            'calc-download': '⬇️ Télécharger',
            'calc-new-calc': '↺ Nouveau calcul',
            'calc-modify': '← Modifier',

            /* ── Summary breakdown ── */
            'calc-sum-sect-base':    'TARIF DE BASE',
            'calc-sum-sect-navette': 'NAVETTE',
            'calc-sum-sect-dispo':   'TOURNÉE / DISPO',
            'calc-sum-sect-waiting': "TEMPS D'ATTENTE",
            'calc-sum-sect-stops':   'EXTRA ARRÊTS',
            'calc-sum-sect-supps':   'SUPPLÉMENTS',
            'calc-sum-sect-fuel':    'SURCHARGE CARBURANT',
            'calc-sum-prix-bxl':     'Prix Bruxelles',
            'calc-sum-prix-rand':    'Prix Rand / Banlieue',
            'calc-sum-prix-prov-min':'Prix Province min.',
            'calc-sum-prix-prov-km': 'Prix Province / km',
            'calc-sum-taxe-km':      'Taxe kilométrique',
            'calc-sum-taxe-km-na':   'Non applicable pour ce véhicule',
            'calc-sum-dispo-na':     'Non disponible pour ce véhicule',
            'calc-sum-km-supp':      'Km supp.',
            'calc-sum-attente':      'Attente',
            'calc-sum-min-incl':     'min inclus',
            'calc-sum-stops-bxl':    'Extra arrêts Bruxelles',
            'calc-sum-stops-other':  'Extra arrêts autres',
            'calc-sum-taxe-stops':   'Taxe km extra arrêts autres',
            'calc-sum-supp-night':   'Supplément nuit',
            'calc-sum-frigo12':      'Nuit frigo -12°C/0°C',
            'calc-sum-frigo20':      'Nuit frigo 0°C/-20°C',
            'calc-sum-convoyeur':    'Convoyeur',
            'calc-sum-chauffeur':    '2e Chauffeur',
            'calc-sum-fuel-label':   'Surcharge carburant',
            'calc-sum-fuel-note':    '⚠ % variable — vérifier mensuellement',
            'calc-sum-subtotal':     'Sous-total HTVA',
            'calc-sum-vat':          'TVA 21%',
            'calc-sum-total-ttc':    'TOTAL TTC',
            'calc-sum-total-htva':   'TOTAL HTVA',
            'calc-sum-vat-excl':     'TVA 21% (non incluse)',
            'calc-sum-auto-sel':     'Sélection automatique — plus petit véhicule valide',
            'calc-sum-manual-sel':   '⚠ Sélection manuelle (override opérateur)',
            'calc-sum-no-vehicle':   'Aucun véhicule compatible',
            'calc-sum-no-vehicle-sub': 'Ajustez les paramètres ou utilisez la sélection manuelle',
            'calc-sum-temps-incl':   'Temps inclus :',

            /* ── Footer (desktop) ── */
            'footer-col1-p1': 'Solutions de transport professionnel de 1 gramme à 30 tonnes.',
            'footer-col1-p2': 'Fiabilité, rapidité et expertise depuis plus de 20 ans.',
            'footer-col2-title': 'Services',
            'footer-nat': 'Transport National',
            'footer-intl': 'Transport International',
            'footer-fleet': 'Notre Flotte',
            'footer-process': 'Notre Process',
            'footer-col3-title': 'Entreprise',
            'footer-about': 'Qui Sommes-Nous',
            'footer-contact': 'Contact',
            'footer-quote-link': 'Faire un Devis',
            'footer-legal': 'Mentions Légales',
            'footer-col4-title': 'Contact',
            'footer-location': 'Brussels Airport<br>Machelen, Belgique',
            'footer-copy': '© 2026 Number One Transport. Tous droits réservés.',

            /* ── more.html ── */
            'back-label': 'Retour',
            'qsn-title': 'Qui sommes<br>nous ?',
            'qsn-intro': 'Nous nous occupons de vos envois les plus urgents vers/depuis la Belgique ou tous les pays européens !',
            'qsn-slogan-label': 'Notre slogan :',
            'qsn-slogan-bar': '« De 1 gramme à 30 tonnes » !',
            'qsn-text': 'Nous sommes une entreprise familiale, active dans le secteur du transport depuis plus de 25 ans. Le sérieux, la rigueur, la rapidité et le suivi administratif sont synonymes, pour notre société, de gage de confiance.',
            'charroi-text': 'Notre charroi de +/- 30 camions et camionnettes nous permet d\'assurer les transports de plus de 400 clients fidèles, depuis l\'artisan jusqu\'à la multinationale en passant bien sûr par la PME.',
            'colis-top': 'Nous nous occupons de vos envois les plus urgents vers/depuis la Belgique ou tous les <strong>pays européens.</strong>',
            'colis-bottom': 'Vos plis et enveloppes, palettes ou autres colis sont retirés et livrés <strong>immédiatement</strong> et dans la foulée.',
            'solution-banner': 'Quelle que soit <strong>votre demande,</strong><br>nous avons <strong>Votre Solution.</strong>',
            'solution-p1': 'Les <strong>compétences</strong> de notre équipe expérimentée permettent à Number One de vous accompagner pour toutes vos activités.',
            'solution-p2': 'Nous vous proposons des <strong>solutions</strong> sur mesure, <strong>adaptées à vos besoins</strong> spécifiques.',
            'repondons': 'Nous répondons, <span class="hl">depuis plus de 25 ans</span> déjà, aux demandes de nos clients issus des secteurs les plus variés.',
            'persuades-p1': 'Nous sommes <strong>persuadés</strong> qu\'une collaboration avec un partenaire de transport fiable pour vous accompagner, ne peut qu\'apporter une <strong>plus-value importante</strong> à votre société.',
            'persuades-p2': 'Notre site Internet remanié est destiné à vous offrir un outil que nous voulons <b>pratique, convivial</b> et <b>interactif</b> particulièrement, grâce à notre « portail clients ».',
            /* ── transport.html ── */
            'transport-subtitle': 'National et international',
            'transport-spec': 'Notre spécialisation depuis plus de 25 ans',
            'transport-p1': "Notre dénomination n'est pas usurpée, nous sommes les \u00ab\u00a0Number One\u00a0\u00bb dans notre secteur.",
            'transport-p2': "Notre équipe de près de 70 professionnels est à votre service pour vous apporter <strong>LA Solution</strong> dont vous avez besoin.",
            'transport-p3': 'Nous nous chargeons de vos envois urgents vers/depuis la Belgique ou tous les pays européens.',
            'transport-p4': "Plis, palettes ou colis volumineux sont retirés et livrés dans la foulée. Notre importante flotte de véhicules nous permet de vous proposer le véhicule parfaitement adapté à vos besoins (depuis la simple voiture jusqu'au semi-remorque). Nos chauffeurs-livreurs peuvent vous aider en matière de manutention\u00a0… Tout comme nos dispatcheurs et les autres membres de notre personnel, ils sont à votre service\u00a0!",
            'transport-cta': 'NOUS CONTACTER',
            'express-title': 'Transport Express',
            'express-p1': "Enlèvement et livraison rapides partout en Belgique et en Europe. De la simple enveloppe à la palette, nous avons le véhicule adapté — et une équipe prête à vous assister à chaque étape.",
            'eco-page-title': 'ÉCONOMIQUE',
            'eco-how-title': 'Comment ça fonctionne ?',
            'eco-details-btn': 'Détails',
            'eco-title': 'Service Économie',
            'eco-tagline': '40 % de réduction sur le tarif express',
            'eco-p1': "Cette formule vous permet de bénéficier, sous certaines conditions, d'une réduction attractive de 40% sur le tarif express ! Nous proposons ce service complémentaire à notre clientèle fidèle pour les envois dont les délais de livraison sont plus flexibles. Soyez amplement rassurée : les coûts de vos transports sont allégés mais la qualité de notre service reste inchangée.",
            'eco-li1': "Pour toute commande passée avant 18 heures, vos envois seront livrés dans un délai de 48 heures en Belgique.",
            'eco-li2': "Ce système de navettes a été créé pour tous vos envois qui ne nécessitent pas une livraison « express ». Nous vous demandons donc de bien vouloir cocher la case prévue à cet effet sur notre note d'envoi. À défaut de quoi, les courses seront automatiquement considérées comme des « express ».",
            'eco-li3': "Nous vous proposons de réduire le prix de vos transports de 40%, pour chaque commande passée la veille avant 16h00 et à livrer entre 8h00 et 18h00 le lendemain (J+1).",
            'driver-title': 'Mise à disposition',
            'driver-tagline': "Un chauffeur professionnel à votre service, à l'heure ou à la journée",
            'driver-p1': "Un chauffeur professionnel disponible à l'heure ou à la journée. Idéal en cas de surcharge ou de panne — véhicule de remplacement inclus. Vous ne payez que les heures réellement prestées. Disponible au départ de Bruxelles.",

            /* ── news.html ── */
            'news-hero-line1': 'NOS',
            'news-hero-line2': 'ACTUALITÉS',
            'news-hero-subtitle': 'Restez informé de toutes les nouveautés Number One',
            'news-filter': 'Trier: 5 dernières années',
            'news-badge-new': 'Nouveau',
            'news-1-date': '20 déc. 2020',
            'news-1-title': 'Axe kilométrique en Belgique : modifications dès le 01/01/2019',
            'news-1-excerpt': 'Indexation des tarifs en Wallonie et en Flandre et élargissement du réseau routier en Flandre.',
            'news-2-date': '18 déc. 2018',
            'news-2-title': 'Flandre : élargissement réseau routier soumis à la taxe kilométrique',
            'news-2-excerpt': 'A partir du 01/01/2019, les trois tronçons suivants seront rajoutés au réseau routier soumis à la taxe kilométrique :',
            'news-3-date': '18 déc. 2018',
            'news-3-title': 'Flandre : élargissement réseau routier soumis à la taxe kilométrique',
            'news-3-excerpt': 'A partir du 01/01/2019, les trois tronçons suivants seront rajoutés au réseau routier soumis à la taxe kilométrique :',
            'news-4-date': '18 déc. 2018',
            'news-4-title': 'Flandre : élargissement réseau routier soumis à la taxe kilométrique',
            'news-4-excerpt': 'A partir du 01/01/2019, les trois tronçons suivants seront rajoutés au réseau routier soumis à la taxe kilométrique :',
            'news-road-li1': "l'A11 de Bruges (N31) à Knokke-Heist (N49)",
            'news-road-li2': 'la N36 de Roulers (R32) à Zarren (N35)',
            'news-road-li3': 'la N722 de Hasselt (N80) à Saint-Trond (N718)'
        },

        en: {
            'logo-subtitle': 'From the FB Logistics Group',
            'fb-group-bar': 'From the FB Logistics Group',

            'nav-services': 'Services',
            'nav-process': 'Our Process',
            'nav-fleet': 'Our Fleet',
            'nav-about': 'About Us',
            'nav-news': 'News',
            'nav-quote': 'Get a Quote',

            'menu-home': 'HOME',
            'menu-vehicles': 'VEHICLES',
            'menu-services': 'OUR SERVICES',
            'menu-about': 'ABOUT US',
            'menu-client': 'CLIENT PORTAL',
            'menu-news': 'NEWS',
            'menu-call': 'CALL US',

            'hero-subtitle': 'Dedicated and express transport solutions, reliable and efficient for all your logistics needs',
            'hero-subtitle-mobile': 'Dedicated and express transport solutions,<br>reliable and efficient',

            'cta-info': 'Need a quick solution?',
            'btn-quote': 'Get a Quote',
            'btn-contact': 'Contact Us',

            'services-title': 'OUR SERVICES',
            'services-tagline': 'Solutions tailored to every need',
            'services-tagline-mobile': 'Solutions tailored<br>to every need',
            'svc-transport-name': 'Transport',
            'svc-transport-desc': 'National and international transport solutions tailored to your needs',
            'svc-transport-desc-mobile': 'national &amp; international',
            'svc-eco-name': 'Economical',
            'svc-eco-desc': 'The best value for money for your professional shipments',
            'svc-eco-desc-mobile': 'The best value for money',
            'svc-quote-name': 'NEED A QUOTE?',
            'svc-quote-desc': 'Contact us now for a personalised offer',
            'svc-quote-desc-mobile': 'Contact us now<br>for a personalised offer',

            'process-subtitle': 'from reception to delivery',
            'step1-name': 'RECEPTION',
            'step1-desc': '→ Client contact<br>→ Order intake',
            'step1-desc-mobile': '→ Client contact<br>→ Order intake',
            'step2-name': 'PREPARATION',
            'step2-name-mobile': 'PREPARATION',
            'step2-desc': '→ Assign driver<br>→ Drive to loading point<br>→ Load vehicle',
            'step2-desc-mobile': '→ Assign driver<br>→ Loading point<br>→ Load vehicle',
            'step3-name': 'DELIVERY',
            'step3-desc': '→ Drive to destination<br>→ Unload vehicle<br>→ Sign POD (Proof of Delivery)',
            'step3-desc-mobile': '→ Drive to destination<br>→ Unload vehicle<br>→ Sign POD',

            'fleet-title': 'OUR FLEET',
            'fleet-subtitle': 'OF VEHICLES',
            'fleet-tagline': 'Solutions tailored to every transport need',
            'fleet-tagline-mobile': 'Solutions tailored to every<br>transport need',
            'fleet-cta': 'CHOOSE THE VEHICLE SUITED TO YOUR NEED',
            'fleet-cta-mobile': 'CHOOSE THE VEHICLE<br>SUITED TO YOUR NEED',
            'veh1-name': 'CAR',
            'veh1-desc': 'Ideal for small trips and fast deliveries in urban areas',
            'veh1-desc-mobile': 'Ideal for small trips<br>and fast deliveries.',
            'veh2-name': 'VAN 9 M³ / 4',
            'veh2-desc': 'Optimal volume for larger loads, transported safely',
            'veh2-desc-mobile': 'Optimal volume for larger<br>loads, transported safely.',
            'veh3-name': 'VAN 2.70 m³ / 450 kg',
            'veh3-desc': 'Perfect for small transports and daily deliveries',
            'veh3-desc-mobile': 'Perfect for small transports<br>and daily deliveries.',
            'veh4-name': 'VAN 6 M³ / 4',
            'veh4-desc': 'Ideal for removals and everyday deliveries',
            'veh4-desc-mobile': 'Ideal for removals<br>and everyday deliveries.',

            /* ── Fleet modal ── */
            'veh1-type': 'CAR',               'veh1-subtitle': 'Saloon / City Car',        'veh1-badge': 'Ideal for fast couriers',
            'veh2-type': 'VAN',               'veh2-subtitle': 'Van / Large Volume',       'veh2-badge': 'Ideal for large volumes',
            'veh3-type': 'UTILITY VAN',       'veh3-subtitle': 'Van / Compact',            'veh3-badge': 'Ideal for small volumes',
            'veh4-type': 'VAN',               'veh4-subtitle': 'Van / Standard',           'veh4-badge': 'Ideal for removals',
            'spec-table-title': 'TECHNICAL SPECIFICATIONS',
            'spec-label-volume': 'Useful volume',
            'spec-label-payload': 'Payload',
            'spec-label-security': 'Security',
            'spec-security-value': 'Optimal',
            'spec-length': 'Interior length',
            'spec-height': 'Interior height',
            'spec-width-wheels': 'Interior width between wheels',
            'spec-width-load': 'Loading width',
            'spec-volume': 'Useful volume',
            'spec-payload': 'Payload',
            'veh-select-btn': 'Select this vehicle',

            'stat-vehicles': 'Vehicles',
            'stat-experience': 'Years of experience',
            'stat-solution': 'Unique solution',
            'stat-clients': 'Satisfied clients',
            'stat-vehicles-m': 'vehicles',
            'stat-exp-m': 'years of<br>experience',
            'stat-sol-m': 'unique<br>solution',
            'stat-clients-m': 'Clients',
            'about-title': 'WHO ARE WE?',
            'about-title-mobile': 'WHO ARE<br>WE?',
            'about-p1': 'For over 25 years, <span class="highlight">Number One</span> has been a specialist in express transport in Belgium and across Europe.',
            'about-p2': '<span class="highlight">From 1 gram to 30 tonnes</span>, we handle all your shipments, from letters to oversized freight.',
            'about-p3': 'Our complete fleet — from a simple car to a semi-trailer — and our team of 70 professionals are at your service for every shipment.',
            'about-p4': '<span class="highlight">Reliability, speed</span> and rigour: the values that have made us a trusted partner for over 25 years.',
            'about-btn': 'Learn more',

            /* ── Welcome popup ── */
            'popup-title': 'Welcome to Number One!',
            'popup-body': 'You\'re on the right page for all your transportation needs — national and international. From 1 gram to 30 tonnes, we deliver across Belgium and Europe.',
            'popup-close': 'Explore our services',

            /* ── Contact footer ── */
            'menu-services-link': 'Our services',
            'menu-about-link': 'About us',

            /* ── Calculator ── */
            'calc-step1-l1': 'PRICING', 'calc-step1-l2': 'MODE',
            'calc-step1-sub': 'Choose the pricing mode that matches your needs',
            'calc-step2-l1': 'SHIPMENT', 'calc-step2-l2': 'DETAILS',
            'calc-step2-sub': 'Describe your shipment as precisely as possible',
            'calc-step3-l1': 'VEHICLE', 'calc-step3-l2': 'SELECTION',
            'calc-step3-sub': 'Choose the vehicle suited to your load',
            'calc-step4-l1': 'OPERATIONAL', 'calc-step4-l2': 'SUPPLEMENTS',
            'calc-step4-sub': 'Add the specific options and constraints for your transport',
            'calc-step5-l1': 'FUEL', 'calc-step5-l2': '& VAT',
            'calc-step5-sub': 'Specify the tax options to include in the calculation',
            'calc-sum-l1': 'QUOTE', 'calc-sum-l2': 'SUMMARY',
            'calc-sum-sub': 'Complete summary of your transport request',
            'calc-mode-bxl': 'Brussels / Brussel',
            'calc-mode-bxl-sub': 'City flat rate',
            'calc-mode-prov-min': 'Province min.',
            'calc-mode-prov-min-sub': 'Fixed provincial rate',
            'calc-mode-rand': 'Rand / Suburb',
            'calc-mode-rand-sub': 'Suburban rate',
            'calc-mode-prov-km': 'Province / Km',
            'calc-mode-prov-km-sub': 'Per kilometre rate',
            'calc-mode-navette': 'Shuttle',
            'calc-mode-navette-sub': 'Fixed shuttle rate',
            'calc-mode-dispo': 'Tour / On-call',
            'calc-mode-dispo-sub': 'Hourly rate',
            'calc-distance': 'Distance (km)',
            'calc-zone-navette': 'Shuttle zone',
            'calc-nav-bxl': 'Bxl / Brussels — €6.65',
            'calc-nav-rand': 'Suburb / Rand — €7.76',
            'calc-nav-brabant': 'Brabant — €12.20',
            'calc-nav-prov': 'Province — €15.25',
            'calc-nav-prov-lux': 'Prov. Lux. — €24.40',
            'calc-nav-export': 'Export (on request)',
            'calc-duree': 'Duration',
            'calc-duree-under6': 'Less than 6h',
            'calc-duree-over6': '6h or more',
            'calc-heures': 'Hours',
            'calc-km-supp': 'Extra kilometres',
            'calc-next': 'Next',
            'calc-back': '← Back',
            'calc-palettes': 'PALLETS',
            'calc-poids': 'WEIGHT (Kg)',
            'calc-hauteur': 'HEIGHT',
            'calc-longueur': 'LENGTH',
            'calc-largeur': 'WIDTH',
            'calc-volume': 'VOLUME (M³)',
            'calc-optional': '(optional)',
            'calc-frigo': 'Refrigerated transport',
            'calc-temp-range': 'Temperature range',
            'calc-hayon': 'Tail lift required',
            'calc-choose-vehicle': 'CHOOSE THE VEHICLE SUITED TO YOUR NEEDS',
            'calc-override': 'Manual selection (override)',
            'calc-debug': '▶ Selection details (show/hide)',
            'calc-waiting': 'TOTAL WAITING TIME (MIN)',
            'calc-stops-bxl': 'EXTRA STOP BRUSSELS',
            'calc-stops-other': 'EXTRA STOP OTHER',
            'calc-supp-night': 'Night supplement',
            'calc-frigo-night-12': 'Night fridge -12/0°C',
            'calc-frigo-night-20': 'Night fridge 0/-20°C',
            'calc-convoyeur': 'ESCORT (HOURS)',
            'calc-convoyeur-rate': '€40.89 / hour',
            'calc-chauffeur': '2nd DRIVER (HOURS)',
            'calc-chauffeur-rate': '€47.93 / hour',
            'calc-fuel-label': 'Apply fuel surcharge',
            'calc-fuel-sub': 'Add the fuel surcharge to the quote',
            'calc-fuel-pct': '% Fuel surcharge',
            'calc-fuel-warning': '⚠ Variable value — check monthly. Example Dec. 2025: 19.50%',
            'calc-vat-label': 'Show price incl. VAT (21%)',
            'calc-vat-sub': 'Add VAT to the quote',
            'calc-resume': 'SUMMARISE',
            'calc-disclaimer': 'This calculator is based on the 2026 tariff. The final price remains subject to commercial verification. All prices are excluding VAT (21%).',
            'calc-print': '🖨️ Print',
            'calc-download': '⬇️ Download',
            'calc-new-calc': '↺ New calculation',
            'calc-modify': '← Edit',

            /* ── Summary breakdown ── */
            'calc-sum-sect-base':    'BASE RATE',
            'calc-sum-sect-navette': 'SHUTTLE',
            'calc-sum-sect-dispo':   'TOUR / ON-CALL',
            'calc-sum-sect-waiting': 'WAITING TIME',
            'calc-sum-sect-stops':   'EXTRA STOPS',
            'calc-sum-sect-supps':   'SUPPLEMENTS',
            'calc-sum-sect-fuel':    'FUEL SURCHARGE',
            'calc-sum-prix-bxl':     'Brussels price',
            'calc-sum-prix-rand':    'Rand / Suburb price',
            'calc-sum-prix-prov-min':'Province min. price',
            'calc-sum-prix-prov-km': 'Province / km price',
            'calc-sum-taxe-km':      'Kilometre tax',
            'calc-sum-taxe-km-na':   'Not applicable for this vehicle',
            'calc-sum-dispo-na':     'Not available for this vehicle',
            'calc-sum-km-supp':      'Extra km',
            'calc-sum-attente':      'Waiting',
            'calc-sum-min-incl':     'min included',
            'calc-sum-stops-bxl':    'Extra stops Brussels',
            'calc-sum-stops-other':  'Extra stops other',
            'calc-sum-taxe-stops':   'Km tax extra stops other',
            'calc-sum-supp-night':   'Night supplement',
            'calc-sum-frigo12':      'Night fridge -12°C/0°C',
            'calc-sum-frigo20':      'Night fridge 0°C/-20°C',
            'calc-sum-convoyeur':    'Escort',
            'calc-sum-chauffeur':    '2nd Driver',
            'calc-sum-fuel-label':   'Fuel surcharge',
            'calc-sum-fuel-note':    '⚠ % variable — check monthly',
            'calc-sum-subtotal':     'Subtotal excl. VAT',
            'calc-sum-vat':          'VAT 21%',
            'calc-sum-total-ttc':    'TOTAL incl. VAT',
            'calc-sum-total-htva':   'TOTAL excl. VAT',
            'calc-sum-vat-excl':     'VAT 21% (not included)',
            'calc-sum-auto-sel':     'Automatic selection — smallest valid vehicle',
            'calc-sum-manual-sel':   '⚠ Manual selection (operator override)',
            'calc-sum-no-vehicle':   'No compatible vehicle',
            'calc-sum-no-vehicle-sub': 'Adjust parameters or use manual selection',
            'calc-sum-temps-incl':   'Time included:',

            'footer-col1-p1': 'Professional transport solutions from 1 gram to 30 tonnes.',
            'footer-col1-p2': 'Reliability, speed and expertise for over 20 years.',
            'footer-col2-title': 'Services',
            'footer-nat': 'National Transport',
            'footer-intl': 'International Transport',
            'footer-fleet': 'Our Fleet',
            'footer-process': 'Our Process',
            'footer-col3-title': 'Company',
            'footer-about': 'About Us',
            'footer-contact': 'Contact',
            'footer-quote-link': 'Get a Quote',
            'footer-legal': 'Legal Notice',
            'footer-col4-title': 'Contact',
            'footer-location': 'Brussels Airport<br>Machelen, Belgium',
            'footer-copy': '© 2026 Number One Transport. All rights reserved.',

            'back-label': 'Back',
            'qsn-title': 'Who are<br>we?',
            'qsn-intro': 'We handle your most urgent shipments to/from Belgium or any European country!',
            'about-spec': 'Our specialisation for over 25 years',
            'qsn-slogan-label': 'Our slogan:',
            'qsn-slogan-bar': '"From 1 gram to 30 tonnes"!',
            'qsn-text': 'We are a family business, active in the transport sector for over 25 years. Professionalism, rigour, speed and administrative follow-up are, for our company, synonymous with trust.',
            'charroi-text': 'Our fleet of +/- 30 lorries and vans enables us to serve over 400 loyal clients, from craftsmen to multinationals, and of course SMEs.',
            'colis-top': 'We handle your most urgent shipments to/from Belgium or any <strong>European country.</strong>',
            'colis-bottom': 'Your letters, envelopes, pallets or other parcels are collected and delivered <strong>immediately</strong> and without delay.',
            'solution-banner': 'Whatever your <strong>request,</strong><br>we have <strong>Your Solution.</strong>',
            'solution-p1': 'The <strong>expertise</strong> of our experienced team allows Number One to support you in all your activities.',
            'solution-p2': 'We offer <strong>tailored solutions</strong>, <strong>adapted to your specific needs</strong>.',
            'repondons': 'We have been responding, <span class="hl">for over 25 years</span>, to the needs of our clients from the most diverse sectors.',
            'persuades-p1': 'We are <strong>convinced</strong> that working with a reliable transport partner can only bring <strong>significant added value</strong> to your business.',
            'persuades-p2': 'Our redesigned website aims to offer you a tool that is <b>practical, user-friendly</b> and <b>interactive</b>, particularly through our "client portal".',
            /* ── transport.html ── */
            'transport-subtitle': 'National &amp; international',
            'transport-spec': 'Our specialisation for over 25 years',
            'transport-p1': 'Our name is not taken lightly — we truly are the «\u00a0Number One\u00a0» in our sector.',
            'transport-p2': 'Our team of nearly 70 professionals is at your service to bring you <strong>THE Solution</strong> you need.',
            'transport-p3': 'We handle your urgent shipments to/from Belgium or any European country.',
            'transport-p4': 'Letters, pallets or bulky parcels are collected and delivered without delay. Our large fleet of vehicles allows us to offer you the perfectly suited vehicle for your needs (from a simple car to a semi-trailer). Our driver-deliverers can assist with handling\u00a0… Just like our dispatchers and other staff members, they are at your service\u00a0!',
            'transport-cta': 'CONTACT US',
            'express-title': 'Express Transport',
            'express-p1': 'Fast collection and delivery across Belgium and Europe. From a single envelope to a full pallet, we have the right vehicle — and a team ready to assist you every step of the way.',
            'eco-page-title': 'ECONOMICAL',
            'eco-how-title': 'How does it work?',
            'eco-title': 'Economy Service',
            'eco-tagline': '40% discount on the express rate',
            'eco-p1': "This formula allows you, under certain conditions, to benefit from an attractive 40% discount on the express rate! We offer this complementary service to our loyal customers for shipments with more flexible delivery deadlines. Rest assured: your transport costs are reduced, but the quality of our service remains unchanged.",
            'eco-li1': 'For any order placed before 6 pm, your shipments will be delivered within 48 hours in Belgium.',
            'eco-li2': "This shuttle system was created for shipments that do not require express delivery. Please tick the relevant box on our shipping note — otherwise courses will automatically be treated as express.",
            'eco-li3': '40% reduction for any order placed the day before before 4 pm, for delivery between 8 am and 6 pm the following day (D+1).',
            'driver-title': 'Vehicle with Driver',
            'driver-tagline': 'A professional driver at your service, by the hour or the day',
            'driver-p1': "A professional driver available by the hour or full day. Ideal for work overload or fleet issues — replacement vehicle included. You only pay for hours actually worked. Available from Brussels.",

            /* ── news.html ── */
            'news-hero-line1': 'OUR',
            'news-hero-line2': 'NEWS',
            'news-hero-subtitle': 'Stay informed about all the latest updates from Number One',
            'news-filter': 'Sort: Last 5 years',
            'news-badge-new': 'New',
            'news-1-date': '20 Dec. 2020',
            'news-1-title': 'Kilometer tax in Belgium: changes from 01/01/2019',
            'news-1-excerpt': 'Indexation of rates in Wallonia and Flanders and expansion of the road network in Flanders.',
            'news-2-date': '18 Dec. 2018',
            'news-2-title': 'Flanders: road network expansion subject to kilometer tax',
            'news-2-excerpt': 'From 01/01/2019, the following three sections will be added to the road network subject to the kilometer tax:',
            'news-3-date': '18 Dec. 2018',
            'news-3-title': 'Flanders: road network expansion subject to kilometer tax',
            'news-3-excerpt': 'From 01/01/2019, the following three sections will be added to the road network subject to the kilometer tax:',
            'news-4-date': '18 Dec. 2018',
            'news-4-title': 'Flanders: road network expansion subject to kilometer tax',
            'news-4-excerpt': 'From 01/01/2019, the following three sections will be added to the road network subject to the kilometer tax:',
            'news-road-li1': 'the A11 from Bruges (N31) to Knokke-Heist (N49)',
            'news-road-li2': 'the N36 from Roeselare (R32) to Zarren (N35)',
            'news-road-li3': 'the N722 from Hasselt (N80) to Sint-Truiden (N718)'
        },

        nl: {
            'logo-subtitle': 'Van de FB Logistics Groep',
            'fb-group-bar': 'Van de FB Logistics Groep',

            'nav-services': 'Diensten',
            'nav-process': 'Ons Proces',
            'nav-fleet': 'Onze Vloot',
            'nav-about': 'Over Ons',
            'nav-news': 'Nieuws',
            'nav-quote': 'Offerte aanvragen',

            'menu-home': 'STARTPAGINA',
            'menu-vehicles': 'VOERTUIGEN',
            'menu-services': 'ONZE DIENSTEN',
            'menu-about': 'OVER ONS',
            'menu-client': 'KLANTENPORTAAL',
            'menu-news': 'NIEUWS',
            'menu-call': 'BELLEN',

            'hero-subtitle': 'Toegewijde en express transportoplossingen, betrouwbaar en efficiënt voor al uw logistieke behoeften',
            'hero-subtitle-mobile': 'Toegewijde en express transportoplossingen,<br>betrouwbaar en efficiënt',

            'cta-info': 'Heeft u snel een oplossing nodig?',
            'btn-quote': 'Offerte aanvragen',
            'btn-contact': 'Neem contact op',

            'services-title': 'ONZE DIENSTEN',
            'services-tagline': 'Oplossingen op maat van elke behoefte',
            'services-tagline-mobile': 'Oplossingen op maat<br>van elke behoefte',
            'svc-transport-name': 'Transport',
            'svc-transport-desc': 'Nationale en internationale transportoplossingen op maat van uw behoeften',
            'svc-transport-desc-mobile': 'nationaal &amp; internationaal',
            'svc-eco-name': 'Economisch',
            'svc-eco-desc': 'De beste prijs-kwaliteitsverhouding voor uw professionele zendingen',
            'svc-eco-desc-mobile': 'De beste prijs-kwaliteitsverhouding',
            'svc-quote-name': 'OFFERTE NODIG?',
            'svc-quote-desc': 'Neem nu contact met ons op voor een persoonlijk aanbod',
            'svc-quote-desc-mobile': 'Neem nu contact op<br>voor een persoonlijk aanbod',

            'process-subtitle': 'van ontvangst tot levering',
            'step1-name': 'ONTVANGST',
            'step1-desc': '→ Klantcontact<br>→ Orderopname',
            'step1-desc-mobile': '→ Klantcontact<br>→ Orderopname',
            'step2-name': 'VOORBEREIDING',
            'step2-name-mobile': 'VOORBEREIDING',
            'step2-desc': '→ Chauffeur toewijzen<br>→ Rijden naar laadpunt<br>→ Voertuig laden',
            'step2-desc-mobile': '→ Chauffeur toewijzen<br>→ Laadpunt<br>→ Voertuig laden',
            'step3-name': 'LEVERING',
            'step3-desc': '→ Rijden naar de bestemming<br>→ Lossen<br>→ POD ondertekenen (Proof of Delivery)',
            'step3-desc-mobile': '→ Rijden naar bestemming<br>→ Lossen<br>→ POD ondertekenen',

            'fleet-title': 'ONZE VLOOT',
            'fleet-subtitle': 'VAN VOERTUIGEN',
            'fleet-tagline': 'Oplossingen op maat van elke transportbehoefte',
            'fleet-tagline-mobile': 'Oplossingen op maat van elke<br>transportbehoefte',
            'fleet-cta': 'KIES HET VOERTUIG DAT PAST BIJ UW BEHOEFTE',
            'fleet-cta-mobile': 'KIES HET VOERTUIG<br>DAT PAST BIJ UW BEHOEFTE',
            'veh1-name': 'PERSONENWAGEN',
            'veh1-desc': 'Ideaal voor kleine verplaatsingen en snelle leveringen in stedelijk gebied',
            'veh1-desc-mobile': 'Ideaal voor kleine verplaatsingen<br>en snelle leveringen.',
            'veh2-name': 'BESTELWAGEN 9 M³ / 4',
            'veh2-desc': 'Optimaal volume voor grotere ladingen, veilig vervoerd',
            'veh2-desc-mobile': 'Optimaal volume voor grotere<br>ladingen, veilig vervoerd.',
            'veh3-name': 'BESTELWAGEN 2,70 m³ / 450 kg',
            'veh3-desc': 'Perfect voor kleine transporten en dagelijkse leveringen',
            'veh3-desc-mobile': 'Perfect voor kleine transporten<br>en dagelijkse leveringen.',
            'veh4-name': 'BESTELWAGEN 6 M³ / 4',
            'veh4-desc': 'Ideaal voor verhuizingen en dagelijkse leveringen',
            'veh4-desc-mobile': 'Ideaal voor verhuizingen<br>en dagelijkse leveringen.',

            /* ── Fleet modal ── */
            'veh1-type': 'PERSONENWAGEN',     'veh1-subtitle': 'Sedan / Stadswagen',       'veh1-badge': 'Ideaal voor snelle koeriers',
            'veh2-type': 'BESTELWAGEN',        'veh2-subtitle': 'Bestelwagen / Groot Volume','veh2-badge': 'Ideaal voor grote volumes',
            'veh3-type': 'UTILITAIRE',         'veh3-subtitle': 'Bestelwagen / Compact',    'veh3-badge': 'Ideaal voor kleine volumes',
            'veh4-type': 'BESTELWAGEN',        'veh4-subtitle': 'Bestelwagen / Standaard',  'veh4-badge': 'Ideaal voor verhuizingen',
            'spec-table-title': 'TECHNISCHE SPECIFICATIES',
            'spec-label-volume': 'Nuttig volume',
            'spec-label-payload': 'Laadvermogen',
            'spec-label-security': 'Veiligheid',
            'spec-security-value': 'Optimaal',
            'spec-length': 'Interne lengte',
            'spec-height': 'Interne hoogte',
            'spec-width-wheels': 'Interne breedte tussen wielen',
            'spec-width-load': 'Laadbreedte',
            'spec-volume': 'Nuttig volume',
            'spec-payload': 'Laadvermogen',
            'veh-select-btn': 'Selecteer dit voertuig',

            'stat-vehicles': 'Voertuigen',
            'stat-experience': 'Jaar ervaring',
            'stat-solution': 'Unieke oplossing',
            'stat-clients': 'Tevreden klanten',
            'stat-vehicles-m': 'voertuigen',
            'stat-exp-m': 'jaar<br>ervaring',
            'stat-sol-m': 'unieke<br>oplossing',
            'stat-clients-m': 'Klanten',
            'about-title': 'WIE ZIJN WIJ?',
            'about-title-mobile': 'WIE ZIJN<br>WIJ?',
            'about-p1': 'Sinds meer dan 25 jaar is <span class="highlight">Number One</span> specialist in expresvervoer in België en Europa.',
            'about-p2': '<span class="highlight">Van 1 gram tot 30 ton</span>, wij verwerken al uw zendingen, van brieven tot volumineuze goederen.',
            'about-p3': 'Onze complete vloot — van een eenvoudige auto tot een oplegger — en ons team van 70 professionals staan klaar voor elke zending.',
            'about-p4': '<span class="highlight">Betrouwbaarheid, snelheid</span> en nauwgezetheid: de waarden die ons al meer dan 25 jaar een vertrouwde partner maken.',
            'about-btn': 'Meer informatie',

            /* ── Welcome popup ── */
            'popup-title': 'Welkom bij Number One!',
            'popup-body': 'U bent op de juiste pagina voor al uw transportbehoeften — nationaal en internationaal. Van 1 gram tot 30 ton, wij leveren door heel België en Europa.',
            'popup-close': 'Ontdek onze diensten',

            /* ── Contact footer ── */
            'menu-services-link': 'Onze diensten',
            'menu-about-link': 'Over ons',

            /* ── Calculator ── */
            'calc-step1-l1': 'TARIFICATIE', 'calc-step1-l2': 'MODUS',
            'calc-step1-sub': 'Kies de tariefmethode die bij uw behoefte past',
            'calc-step2-l1': 'KENMERKEN', 'calc-step2-l2': 'VAN DE LADING',
            'calc-step2-sub': 'Beschrijf uw lading zo nauwkeurig mogelijk',
            'calc-step3-l1': 'VOERTUIG', 'calc-step3-l2': 'SELECTIE',
            'calc-step3-sub': 'Kies het voertuig dat bij uw lading past',
            'calc-step4-l1': 'OPERATIONELE', 'calc-step4-l2': 'SUPPLEMENTEN',
            'calc-step4-sub': 'Voeg de specifieke opties en beperkingen toe voor uw transport',
            'calc-step5-l1': 'BRANDSTOF', 'calc-step5-l2': '& BTW',
            'calc-step5-sub': 'Geef de fiscale opties op die in de berekening moeten worden opgenomen',
            'calc-sum-l1': 'OFFERTE', 'calc-sum-l2': 'SAMENVATTING',
            'calc-sum-sub': 'Volledig overzicht van uw transportaanvraag',
            'calc-mode-bxl': 'Brussel / Bruxelles',
            'calc-mode-bxl-sub': 'Vaste stadsprijs',
            'calc-mode-prov-min': 'Provincie min.',
            'calc-mode-prov-min-sub': 'Vaste provinciale prijs',
            'calc-mode-rand': 'Rand / Banlieue',
            'calc-mode-rand-sub': 'Prijs randgebied',
            'calc-mode-prov-km': 'Provincie / Km',
            'calc-mode-prov-km-sub': 'Prijs per kilometer',
            'calc-mode-navette': 'Navette',
            'calc-mode-navette-sub': 'Vaste navetteprijs',
            'calc-mode-dispo': 'Ronde / Beschikbaar',
            'calc-mode-dispo-sub': 'Uurtarief',
            'calc-distance': 'Afstand (km)',
            'calc-zone-navette': 'Navettezone',
            'calc-nav-bxl': 'Bxl / Brussel — €6.65',
            'calc-nav-rand': 'Rand / Banlieue — €7.76',
            'calc-nav-brabant': 'Brabant — €12.20',
            'calc-nav-prov': 'Prov. — €15.25',
            'calc-nav-prov-lux': 'Prov. Lux. — €24.40',
            'calc-nav-export': 'Export (op aanvraag)',
            'calc-duree': 'Duur',
            'calc-duree-under6': 'Minder dan 6u',
            'calc-duree-over6': '6u of meer',
            'calc-heures': 'Uren',
            'calc-km-supp': 'Extra kilometers',
            'calc-next': 'Volgende',
            'calc-back': '← Terug',
            'calc-palettes': 'PALLETS',
            'calc-poids': 'GEWICHT (Kg)',
            'calc-hauteur': 'HOOGTE',
            'calc-longueur': 'LENGTE',
            'calc-largeur': 'BREEDTE',
            'calc-volume': 'VOLUME (M³)',
            'calc-optional': '(optioneel)',
            'calc-frigo': 'Gekoeld transport',
            'calc-temp-range': 'Temperatuurbereik',
            'calc-hayon': 'Laadklep vereist',
            'calc-choose-vehicle': 'KIES HET VOERTUIG DAT BIJ UW BEHOEFTE PAST',
            'calc-override': 'Handmatige selectie (override)',
            'calc-debug': '▶ Selectiedetails (weergeven/verbergen)',
            'calc-waiting': 'TOTALE WACHTTIJD (MIN)',
            'calc-stops-bxl': 'EXTRA STOP BRUSSEL',
            'calc-stops-other': 'EXTRA STOP OVERIG',
            'calc-supp-night': 'Nachttoeslag',
            'calc-frigo-night-12': 'Nacht koelwagen -12/0°C',
            'calc-frigo-night-20': 'Nacht koelwagen 0/-20°C',
            'calc-convoyeur': 'BEGELEIDER (UREN)',
            'calc-convoyeur-rate': '€40.89 / uur',
            'calc-chauffeur': '2e CHAUFFEUR (UREN)',
            'calc-chauffeur-rate': '€47.93 / uur',
            'calc-fuel-label': 'Brandstoftoeslag toepassen',
            'calc-fuel-sub': 'Voeg de brandstoftoeslag toe aan de offerte',
            'calc-fuel-pct': '% Brandstoftoeslag',
            'calc-fuel-warning': '⚠ Variabele waarde — maandelijks controleren. Voorbeeld dec. 2025: 19,50%',
            'calc-vat-label': 'Prijs incl. BTW tonen (21%)',
            'calc-vat-sub': 'BTW toevoegen aan de offerte',
            'calc-resume': 'SAMENVATTEN',
            'calc-disclaimer': 'Deze calculator is gebaseerd op het tarief van 2026. De uiteindelijke prijs blijft onderworpen aan commerciële verificatie. Alle prijzen zijn exclusief BTW (21%).',
            'calc-print': '🖨️ Afdrukken',
            'calc-download': '⬇️ Downloaden',
            'calc-new-calc': '↺ Nieuwe berekening',
            'calc-modify': '← Bewerken',

            /* ── Summary breakdown ── */
            'calc-sum-sect-base':    'BASISTARIEVEN',
            'calc-sum-sect-navette': 'NAVETTE',
            'calc-sum-sect-dispo':   'RONDE / BESCHIKBAAR',
            'calc-sum-sect-waiting': 'WACHTTIJD',
            'calc-sum-sect-stops':   'EXTRA STOPS',
            'calc-sum-sect-supps':   'SUPPLEMENTEN',
            'calc-sum-sect-fuel':    'BRANDSTOFTOESLAG',
            'calc-sum-prix-bxl':     'Prijs Brussel',
            'calc-sum-prix-rand':    'Prijs Rand / Banlieue',
            'calc-sum-prix-prov-min':'Prijs Provincie min.',
            'calc-sum-prix-prov-km': 'Prijs Provincie / km',
            'calc-sum-taxe-km':      'Kilometerheffing',
            'calc-sum-taxe-km-na':   'Niet van toepassing voor dit voertuig',
            'calc-sum-dispo-na':     'Niet beschikbaar voor dit voertuig',
            'calc-sum-km-supp':      'Extra km',
            'calc-sum-attente':      'Wachttijd',
            'calc-sum-min-incl':     'min inbegrepen',
            'calc-sum-stops-bxl':    'Extra stops Brussel',
            'calc-sum-stops-other':  'Extra stops overig',
            'calc-sum-taxe-stops':   'Km-heffing extra stops overig',
            'calc-sum-supp-night':   'Nachttoeslag',
            'calc-sum-frigo12':      'Nacht koelwagen -12°C/0°C',
            'calc-sum-frigo20':      'Nacht koelwagen 0°C/-20°C',
            'calc-sum-convoyeur':    'Begeleider',
            'calc-sum-chauffeur':    '2e Chauffeur',
            'calc-sum-fuel-label':   'Brandstoftoeslag',
            'calc-sum-fuel-note':    '⚠ % variabel — maandelijks controleren',
            'calc-sum-subtotal':     'Subtotaal excl. BTW',
            'calc-sum-vat':          'BTW 21%',
            'calc-sum-total-ttc':    'TOTAAL incl. BTW',
            'calc-sum-total-htva':   'TOTAAL excl. BTW',
            'calc-sum-vat-excl':     'BTW 21% (niet inbegrepen)',
            'calc-sum-auto-sel':     'Automatische selectie — kleinste geldig voertuig',
            'calc-sum-manual-sel':   '⚠ Handmatige selectie (operator override)',
            'calc-sum-no-vehicle':   'Geen geschikt voertuig',
            'calc-sum-no-vehicle-sub': 'Pas de parameters aan of gebruik handmatige selectie',
            'calc-sum-temps-incl':   'Inbegrepen tijd:',

            'footer-col1-p1': 'Professionele transportoplossingen van 1 gram tot 30 ton.',
            'footer-col1-p2': 'Betrouwbaarheid, snelheid en expertise al meer dan 20 jaar.',
            'footer-col2-title': 'Diensten',
            'footer-nat': 'Nationaal Transport',
            'footer-intl': 'Internationaal Transport',
            'footer-fleet': 'Onze Vloot',
            'footer-process': 'Ons Proces',
            'footer-col3-title': 'Bedrijf',
            'footer-about': 'Over Ons',
            'footer-contact': 'Contact',
            'footer-quote-link': 'Offerte aanvragen',
            'footer-legal': 'Juridische Informatie',
            'footer-col4-title': 'Contact',
            'footer-location': 'Brussels Airport<br>Machelen, België',
            'footer-copy': '© 2026 Number One Transport. Alle rechten voorbehouden.',

            'back-label': 'Terug',
            'qsn-title': 'Wie zijn<br>wij?',
            'qsn-intro': 'Wij verzorgen uw meest urgente zendingen naar/vanuit België of alle Europese landen!',
            'about-spec': 'Onze specialisatie sinds meer dan 25 jaar',
            'qsn-slogan-label': 'Onze slogan:',
            'qsn-slogan-bar': '"Van 1 gram tot 30 ton"!',
            'qsn-text': 'Wij zijn een familiebedrijf, actief in de transportsector al meer dan 25 jaar. Ernst, nauwgezetheid, snelheid en administratieve opvolging zijn voor ons bedrijf synoniem met vertrouwen.',
            'charroi-text': 'Ons wagenpark van +/- 30 vrachtwagens en bestelwagens stelt ons in staat meer dan 400 trouwe klanten te bedienen, van ambachtslieden tot multinationals, en uiteraard ook kmo\'s.',
            'colis-top': 'Wij verzorgen uw meest urgente zendingen naar/vanuit België of alle <strong>Europese landen.</strong>',
            'colis-bottom': 'Uw brieven, enveloppen, paletten of andere pakketten worden <strong>onmiddellijk</strong> opgehaald en geleverd.',
            'solution-banner': 'Wat ook uw <strong>vraag is,</strong><br>wij hebben <strong>Uw Oplossing.</strong>',
            'solution-p1': 'De <strong>expertise</strong> van ons ervaren team stelt Number One in staat u bij al uw activiteiten te ondersteunen.',
            'solution-p2': 'Wij bieden <strong>oplossingen op maat</strong>, <strong>aangepast aan uw specifieke behoeften</strong>.',
            'repondons': 'Al meer dan <span class="hl">25 jaar</span> beantwoorden wij de vragen van onze klanten uit de meest uiteenlopende sectoren.',
            'persuades-p1': 'Wij zijn er <strong>van overtuigd</strong> dat samenwerken met een betrouwbare transportpartner enkel een <strong>belangrijke meerwaarde</strong> voor uw bedrijf kan opleveren.',
            'persuades-p2': 'Onze vernieuwde website wil u een tool bieden die <b>praktisch, gebruiksvriendelijk</b> en <b>interactief</b> is, met name dankzij ons "klantenportaal".',
            /* ── transport.html ── */
            'transport-subtitle': 'Nationaal &amp; internationaal',
            'transport-spec': 'Onze specialisatie al meer dan 25 jaar',
            'transport-p1': 'Onze naam is niet aanmatigend — wij zijn werkelijk de «\u00a0Number One\u00a0» in onze sector.',
            'transport-p2': 'Ons team van bijna 70 professionals staat klaar om u <strong>DE Oplossing</strong> te bieden die u nodig heeft.',
            'transport-p3': 'Wij verzorgen uw urgente zendingen naar/vanuit België of alle Europese landen.',
            'transport-p4': "Brieven, paletten of volumineuze pakketten worden opgehaald en onmiddellijk geleverd. Onze grote vloot voertuigen stelt ons in staat u het perfecte voertuig voor uw behoeften aan te bieden (van een eenvoudige auto tot een oplegger). Onze chauffeur-koeriers kunnen helpen bij het hanteren\u00a0… Net zoals onze dispatchers en andere personeelsleden staan zij tot uw dienst\u00a0!",
            'transport-cta': 'NEEM CONTACT OP',
            'express-title': 'Expressvervoer',
            'express-p1': 'Snelle afhaling en levering in heel België en Europa. Van een eenvoudige brief tot een pallet, wij hebben het juiste voertuig — en een team klaar om u bij elke stap te begeleiden.',
            'eco-page-title': 'ECONOMISCH',
            'eco-how-title': 'Hoe werkt het?',
            'eco-title': 'Economiedienst',
            'eco-tagline': '40 % korting op het expresstarief',
            'eco-p1': "Deze formule laat u toe, onder bepaalde voorwaarden, te genieten van een aantrekkelijke korting van 40 % op het expresstarief ! Wij bieden deze aanvullende dienst aan onze trouwe klanten voor zendingen met flexibelere leveringstermijnen. Wees gerust : uw transportkosten worden verlaagd, maar de kwaliteit van onze dienstverlening blijft ongewijzigd.",
            'eco-li1': 'Voor elke bestelling geplaatst vóór 18 u worden uw zendingen binnen 48 u in België geleverd.',
            'eco-li2': "Dit pendelsysteem is gemaakt voor zendingen die geen expreslevering vereisen. Gelieve het betreffende vakje op onze verzendnota aan te kruisen — anders worden de ritten automatisch als express beschouwd.",
            'eco-li3': '40 % korting voor elke bestelling geplaatst de dag voordien vóór 16 u, te leveren tussen 8 u en 18 u de volgende dag (J+1).',
            'driver-title': 'Voertuig met chauffeur',
            'driver-tagline': 'Een professionele chauffeur tot uw beschikking, per uur of per dag',
            'driver-p1': "Een professionele chauffeur beschikbaar per uur of per dag. Ideaal bij overbelasting of vlootproblemen — vervangend voertuig inbegrepen. U betaalt alleen de werkelijk gepresteerde uren. Beschikbaar vanuit Brussel.",

            /* ── news.html ── */
            'news-hero-line1': 'ONS',
            'news-hero-line2': 'NIEUWS',
            'news-hero-subtitle': 'Blijf op de hoogte van al het laatste nieuws van Number One',
            'news-filter': 'Sorteren: Laatste 5 jaar',
            'news-badge-new': 'Nieuw',
            'news-1-date': '20 dec. 2020',
            'news-1-title': 'Kilometerheffing in België: wijzigingen vanaf 01/01/2019',
            'news-1-excerpt': 'Indexering van de tarieven in Wallonië en Vlaanderen en uitbreiding van het wegennet in Vlaanderen.',
            'news-2-date': '18 dec. 2018',
            'news-2-title': 'Vlaanderen: uitbreiding wegennet onderworpen aan kilometerheffing',
            'news-2-excerpt': 'Vanaf 01/01/2019 worden de volgende drie weggedeelten toegevoegd aan het wegennet dat onderworpen is aan de kilometerheffing:',
            'news-3-date': '18 dec. 2018',
            'news-3-title': 'Vlaanderen: uitbreiding wegennet onderworpen aan kilometerheffing',
            'news-3-excerpt': 'Vanaf 01/01/2019 worden de volgende drie weggedeelten toegevoegd aan het wegennet dat onderworpen is aan de kilometerheffing:',
            'news-4-date': '18 dec. 2018',
            'news-4-title': 'Vlaanderen: uitbreiding wegennet onderworpen aan kilometerheffing',
            'news-4-excerpt': 'Vanaf 01/01/2019 worden de volgende drie weggedeelten toegevoegd aan het wegennet dat onderworpen is aan de kilometerheffing:',
            'news-road-li1': 'de A11 van Brugge (N31) naar Knokke-Heist (N49)',
            'news-road-li2': 'de N36 van Roeselare (R32) naar Zarren (N35)',
            'news-road-li3': 'de N722 van Hasselt (N80) naar Sint-Truiden (N718)'
        }
    };

    function applyLang(lang) {
        if (!T[lang]) lang = 'fr';
        var t = T[lang];
        localStorage.setItem('lang', lang);
        document.documentElement.lang = lang;

        document.querySelectorAll('[data-i18n]').forEach(function (el) {
            var key = el.getAttribute('data-i18n');
            if (t[key] !== undefined) el.innerHTML = t[key];
        });

        document.querySelectorAll('[data-i18n-aria]').forEach(function (el) {
            var key = el.getAttribute('data-i18n-aria');
            if (t[key] !== undefined) el.setAttribute('aria-label', t[key]);
        });

        var flagEl = document.getElementById('currentFlag');
        if (flagEl) flagEl.src = FLAGS[lang];

        var codeEl = document.getElementById('currentLangCode');
        if (codeEl) codeEl.textContent = lang.toUpperCase();

        document.querySelectorAll('[data-lang]').forEach(function (btn) {
            btn.classList.toggle('lang-active', btn.getAttribute('data-lang') === lang);
        });
    }

    function initPicker() {
        var btn = document.getElementById('langBtn');
        var dropdown = document.getElementById('langDropdown');
        if (!btn || !dropdown) return;

        /* Inject flag images into dropdown options */
        ['fr', 'nl', 'en'].forEach(function (l) {
            document.querySelectorAll('.lang-flag-' + l).forEach(function (img) {
                img.src = FLAGS[l];
            });
        });

        btn.addEventListener('click', function (e) {
            e.stopPropagation();
            dropdown.classList.toggle('open');
        });

        document.querySelectorAll('[data-lang]').forEach(function (opt) {
            opt.addEventListener('click', function () {
                applyLang(opt.getAttribute('data-lang'));
                dropdown.classList.remove('open');
            });
        });

        document.addEventListener('click', function () {
            dropdown.classList.remove('open');
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        initPicker();
        applyLang(localStorage.getItem('lang') || 'fr');
    });

    /* Expose for calc.js dynamic content */
    window._T = T;
    var _origApplyLang = applyLang;
    applyLang = function(lang) {
        _origApplyLang(lang);
        if (typeof window.onLangChange === 'function') window.onLangChange(lang);
    };
})();
